// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: icq/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/ibc-go/v3/modules/core/02-client/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	crypto "github.com/tendermint/tendermint/proto/tendermint/crypto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitICQResult represents a message type to fulfil a query request.
type MsgSubmitICQResult struct {
	QueryId     uint64           `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Result      []byte           `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Height      *types.Height    `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	FromAddress string           `protobuf:"bytes,4,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Proof       *crypto.ProofOps `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	PeriodicId  uint64           `protobuf:"varint,6,opt,name=periodic_id,json=periodicId,proto3" json:"periodic_id,omitempty"`
}

func (m *MsgSubmitICQResult) Reset()         { *m = MsgSubmitICQResult{} }
func (m *MsgSubmitICQResult) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitICQResult) ProtoMessage()    {}
func (*MsgSubmitICQResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a7c38f713329dd, []int{0}
}
func (m *MsgSubmitICQResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitICQResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitICQResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitICQResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitICQResult.Merge(m, src)
}
func (m *MsgSubmitICQResult) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitICQResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitICQResult.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitICQResult proto.InternalMessageInfo

func (m *MsgSubmitICQResult) GetQueryId() uint64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *MsgSubmitICQResult) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *MsgSubmitICQResult) GetHeight() *types.Height {
	if m != nil {
		return m.Height
	}
	return nil
}

func (m *MsgSubmitICQResult) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgSubmitICQResult) GetProof() *crypto.ProofOps {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgSubmitICQResult) GetPeriodicId() uint64 {
	if m != nil {
		return m.PeriodicId
	}
	return 0
}

type MsgSubmitICQResultResponse struct {
}

func (m *MsgSubmitICQResultResponse) Reset()         { *m = MsgSubmitICQResultResponse{} }
func (m *MsgSubmitICQResultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitICQResultResponse) ProtoMessage()    {}
func (*MsgSubmitICQResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a7c38f713329dd, []int{1}
}
func (m *MsgSubmitICQResultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitICQResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitICQResultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitICQResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitICQResultResponse.Merge(m, src)
}
func (m *MsgSubmitICQResultResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitICQResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitICQResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitICQResultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitICQResult)(nil), "simplyvc.interchainqueries.icq.MsgSubmitICQResult")
	proto.RegisterType((*MsgSubmitICQResultResponse)(nil), "simplyvc.interchainqueries.icq.MsgSubmitICQResultResponse")
}

func init() { proto.RegisterFile("icq/tx.proto", fileDescriptor_88a7c38f713329dd) }

var fileDescriptor_88a7c38f713329dd = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3f, 0x8f, 0xd3, 0x30,
	0x14, 0xaf, 0xb9, 0xbb, 0x00, 0x6e, 0x25, 0x24, 0x0f, 0x28, 0x04, 0xc8, 0x85, 0x9b, 0x32, 0xd9,
	0x4a, 0xd8, 0xd8, 0x80, 0x85, 0x0a, 0x9d, 0x80, 0xb0, 0xb1, 0x54, 0x8d, 0xe3, 0x26, 0x4f, 0x6a,
	0x62, 0xd7, 0x76, 0xaa, 0x66, 0x64, 0x64, 0xe3, 0x63, 0x31, 0x76, 0x64, 0x44, 0xed, 0x37, 0xe0,
	0x13, 0xa0, 0x38, 0xa9, 0x90, 0xa8, 0x84, 0x74, 0x9b, 0xdf, 0xf3, 0xef, 0xfd, 0xfe, 0xf8, 0x19,
	0xcf, 0x80, 0x6f, 0x98, 0xdd, 0x51, 0xa5, 0xa5, 0x95, 0x24, 0x34, 0x50, 0xab, 0x75, 0xb7, 0xe5,
	0x14, 0x1a, 0x2b, 0x34, 0xaf, 0x96, 0xd0, 0x6c, 0x5a, 0xa1, 0x41, 0x18, 0x0a, 0x7c, 0x13, 0x3c,
	0xb7, 0xa2, 0x29, 0x84, 0xae, 0xa1, 0xb1, 0x8c, 0xeb, 0x4e, 0x59, 0xc9, 0x94, 0x96, 0x72, 0x35,
	0x8c, 0x07, 0xd7, 0x90, 0x73, 0xc6, 0xa5, 0x16, 0x8c, 0xaf, 0x41, 0x34, 0x96, 0x6d, 0x93, 0xf1,
	0x34, 0x00, 0x6e, 0x7e, 0x23, 0x4c, 0x6e, 0x4d, 0xf9, 0xb9, 0xcd, 0x6b, 0xb0, 0xf3, 0xb7, 0x9f,
	0x32, 0x61, 0xda, 0xb5, 0x25, 0x4f, 0xf0, 0x83, 0x5e, 0xa5, 0x5b, 0x40, 0xe1, 0xa3, 0x08, 0xc5,
	0x97, 0xd9, 0x7d, 0x57, 0xcf, 0x0b, 0xf2, 0x18, 0x7b, 0xda, 0x81, 0xfc, 0x7b, 0x11, 0x8a, 0x67,
	0xd9, 0x58, 0x91, 0x14, 0x7b, 0x95, 0x80, 0xb2, 0xb2, 0xfe, 0x45, 0x84, 0xe2, 0x69, 0x1a, 0x50,
	0xc8, 0x39, 0xed, 0xb5, 0xe9, 0xa8, 0xb8, 0x4d, 0xe8, 0x3b, 0x87, 0xc8, 0x46, 0x24, 0x79, 0x81,
	0x67, 0x2b, 0x2d, 0xeb, 0xc5, 0xb2, 0x28, 0xb4, 0x30, 0xc6, 0xbf, 0x8c, 0x50, 0xfc, 0x30, 0x9b,
	0xf6, 0xbd, 0xd7, 0x43, 0x8b, 0x24, 0xf8, 0xca, 0x05, 0xf2, 0xaf, 0x1c, 0xeb, 0x53, 0xfa, 0x37,
	0x30, 0x1d, 0x02, 0xd3, 0x8f, 0xfd, 0xfd, 0x07, 0x65, 0xb2, 0x01, 0x49, 0xae, 0xf1, 0x54, 0x09,
	0x0d, 0xb2, 0x00, 0xde, 0xfb, 0xf7, 0x9c, 0x7f, 0x7c, 0x6a, 0xcd, 0x8b, 0x9b, 0x67, 0x38, 0x38,
	0xcf, 0x9c, 0x09, 0xa3, 0x64, 0x63, 0x44, 0xfa, 0x0d, 0xe1, 0x8b, 0x5b, 0x53, 0x92, 0xaf, 0x08,
	0x3f, 0xfa, 0xf7, 0x5d, 0x52, 0xfa, 0xff, 0x7d, 0xd0, 0x73, 0xde, 0xe0, 0xd5, 0xdd, 0x67, 0x4e,
	0x5e, 0xde, 0xbc, 0xff, 0x71, 0x08, 0xd1, 0xfe, 0x10, 0xa2, 0x5f, 0x87, 0x10, 0x7d, 0x3f, 0x86,
	0x93, 0xfd, 0x31, 0x9c, 0xfc, 0x3c, 0x86, 0x93, 0x2f, 0x49, 0x09, 0xb6, 0x6a, 0x73, 0xca, 0x65,
	0xcd, 0x4e, 0xfc, 0xec, 0x8c, 0x9f, 0xed, 0x98, 0xfb, 0x4e, 0x9d, 0x12, 0x26, 0xf7, 0xdc, 0xca,
	0x5f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x98, 0x02, 0x05, 0x92, 0x62, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitICQResult(ctx context.Context, in *MsgSubmitICQResult, opts ...grpc.CallOption) (*MsgSubmitICQResultResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitICQResult(ctx context.Context, in *MsgSubmitICQResult, opts ...grpc.CallOption) (*MsgSubmitICQResultResponse, error) {
	out := new(MsgSubmitICQResultResponse)
	err := c.cc.Invoke(ctx, "/simplyvc.interchainqueries.icq.Msg/SubmitICQResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitICQResult(context.Context, *MsgSubmitICQResult) (*MsgSubmitICQResultResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitICQResult(ctx context.Context, req *MsgSubmitICQResult) (*MsgSubmitICQResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitICQResult not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitICQResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitICQResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitICQResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplyvc.interchainqueries.icq.Msg/SubmitICQResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitICQResult(ctx, req.(*MsgSubmitICQResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simplyvc.interchainqueries.icq.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitICQResult",
			Handler:    _Msg_SubmitICQResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "icq/tx.proto",
}

func (m *MsgSubmitICQResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitICQResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitICQResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PeriodicId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PeriodicId))
		i--
		dAtA[i] = 0x30
	}
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.Height != nil {
		{
			size, err := m.Height.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x12
	}
	if m.QueryId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.QueryId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitICQResultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitICQResultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitICQResultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitICQResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.QueryId != 0 {
		n += 1 + sovTx(uint64(m.QueryId))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Height != nil {
		l = m.Height.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PeriodicId != 0 {
		n += 1 + sovTx(uint64(m.PeriodicId))
	}
	return n
}

func (m *MsgSubmitICQResultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitICQResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitICQResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitICQResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryId", wireType)
			}
			m.QueryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QueryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Height == nil {
				m.Height = &types.Height{}
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &crypto.ProofOps{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodicId", wireType)
			}
			m.PeriodicId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodicId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitICQResultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitICQResultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitICQResultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
